### PR TITLE
[issue-7] protocol switch based on package manager

### PR DESCRIPTION
**Pull request by snake-py**
Resolves https://github.com/snake-py/eject/issues/7

### CODE REVIEW

**Comment by brillout** [comment]
LGTM although it doesn't resolve #7. It doesn't fix the `link:` protocol, the issue being [this](https://github.com/snake-py/eject/issues/7#issue-2662245853).

**Comment by snake-py** [comment]
@brillout I added the workspace logic for pnpm. The question is, if I should add `./ejected/${dependency}` or simply `ejected/*`

**Comment by snake-py** [comment]
Maybe you can help here if this went correct? I ran it here https://github.com/snake-py/eject-test/tree/pnpm-temp 

It created the workspace file, I thought this is enough.

**Comment by brillout** [comment]
:+1: Let me try.

> The question is, if I should add `./ejected/${dependency}` or simply `ejected/*` to the workspace file.

I guess adding `ejected/*` is a bit easier.

**Comment by brillout** [comment]
Actually, looking at https://github.com/snake-py/eject-test/commit/6fe9b337a8b2a26fc99ad7664c6790b1da2d3700 everything looks good :100:

**Comment by snake-py** [comment]
Alright, I went ahead and merged this PR.

**Comment by brillout** [comment]
One last thing. How about we remove `devDependencies` at `ejected/some-lib/package.json`? It's wasteful to install them. Seems like we're then ready to release a functioning version :rocket:

**Comment by brillout** [comment]
Ah, also a small thing: [here](https://github.com/snake-py/eject-test/commit/6fe9b337a8b2a26fc99ad7664c6790b1da2d3700#diff-18ae0a0fab29a7db7aded913fd05f30a2c8f6c104fadae86c9d217091709794cR1-R2) it should be `ejected/*` instead of `ejected/react`.

**Comment by snake-py** [comment]
> How about we remove devDependencies

Well in the current state it does make sense, however considering that we are planing to might let the user bundle the lib it does not. 

I created a issue for it https://github.com/snake-py/eject/issues/12

**Comment by snake-py** [comment]
> Ah, also a small thing: [here](https://github.com/snake-py/eject-test/commit/6fe9b337a8b2a26fc99ad7664c6790b1da2d3700#diff-18ae0a0fab29a7db7aded913fd05f30a2c8f6c104fadae86c9d217091709794cR1-R2) it should be ejected/* instead of ejected/react.

Let me fix that.

**Comment by snake-py** [comment]
@brillout I think it is cleaner as well. See https://github.com/snake-py/eject/pull/13

**Pull request merged**
