### PR TITLE
[issue-7] adjusted workspace file

### PR DESCRIPTION
**Pull request by snake-py**
Follow up of https://github.com/snake-py/eject/pull/11 see test https://github.com/snake-py/eject-test/tree/pnpm-tmp 

Resolves: https://github.com/snake-py/eject/issues/7

### CODE REVIEW

**Comment by brillout** [comment]
I think we should remove the `- ejected/react` entry?

**Comment by snake-py** [comment]
Where do you see this entry? I am only seeing `ejected/*` https://github.com/snake-py/eject-test/blob/pnpm-tmp/pnpm-workspace.yaml

**Comment by brillout** [comment]
I'm seeing it here: https://github.com/snake-py/eject-test/commit/6fe9b337a8b2a26fc99ad7664c6790b1da2d3700

**Comment by snake-py** [comment]
I am not sure, but on the new branch I am not having this commit. I deleted `pnpm-temp` and made a new test on `pnpm-tmp`.

**Comment by brillout** [comment]
:+1: I guess we're good then.

**Pull request merged**
