### PR TITLE
[issue-9] added action

### PR DESCRIPTION
**Pull request by snake-py**
Resolves https://github.com/snake-py/eject/issues/9 (Not done needs some more testing)

### CODE REVIEW

**Comment by snake-py** [comment]
@brillout ready for review

**Comment by brillout** [comment]
The CI test is a bit cumbersome to reproduce locally. I'd use a pnpm monorepo:
 - `packages/eject/` <-- the `eject` source
 - `playground/eject-react/` <-- testbed
 - `playground/eject-vike-react-chakra/` <-- testbed
 - ...

We could additionally add the yarn and npm lock files to `playground/eject-react` in order to test for all three package managers (while doing `rm -r node_modules/` before running the test in order to avoid conflict between the three). AFAICT this should work just fine.

But as you wish, we can also merge your PR as-is.

**Comment by brillout** [comment]
From yarn and npm's perspective, it won't be a monorepo.

As for pnpm, you're right it'd be nice to test it with a non-monorepo setup. Maybe the trick is to simply to *not* add  `playground/*` to pnpm's workspace, so that it isn't actually a monorepo but a bunch of independent `package.json` projects.

**Comment by snake-py** [comment]
How about we add the eject-test project as a git sub module?

**Comment by snake-py** [comment]
I think you are right, 

we can organize this repository in a little different way, and with that in mind:

> Maybe the trick is to simply to not add playground/* to pnpm's workspace, so that it isn't actually a monorepo but a bunch of independent package.json projects.

However, let us merge this for now, and then revisit the issue once https://github.com/snake-py/eject/issues/4 is resolved.

**Comment by brillout** [comment]
:+1:

**Pull request merged**
